# Eclipse Mosquitto Configuration - Smart Parking System
# Listener MQTT TCP (backend + ESP32 lokal)
listener 1883
allow_anonymous true

# Listener WebSocket (frontend browser MQTT.js)
listener 9001
protocol websockets
allow_anonymous true

# Persistence
persistence true
persistence_location /var/lib/mosquitto/

# Logging
log_dest stdout
log_type all

# Message size
message_size_limit 65536
